### ISSUE TITLE
Q: How using this feature?

### ISSUE THREAD

**Issue by torsten-liermann** [kannanekanath/teamcity-envinject-plugin#4]
Hi, sorry I can't speak english... This feature sounds good, but how are you using the properties in following build steps? If abc is referenced by% env.abc%, for example in the next (maven) runner, TeamCity will not run the build, because the parameter is unknown.

Thanks for a hint
Torsten

**Comment by kannanekanath** [comment]
I am not sure I fully understand the question a screenshot might help.

If you are injecting a brand new property via the plugin and you are referencing in a subsequent runner then it is possible Teamcity will think that all necessary parameters are not supplied yet. I am not entirely sure how we can overcome this in the plugin as it is a core Teamcity feature.

You can perhaps workaround this by setting an EMPTY or an invalid environment variable at the project level and then use EnvInject plugin to update the property? Perhaps then Teamcity will allow you to run the build.

**Comment by shiamak101** [comment]
Do you happen to have a good example (similar to the way this plugin works in Jenkins) for the teamcity?

**Comment by shiamak101** [comment]
I am using a .properties file with a key=value pair but when I run teamcity job I get following error Exception occured reading/parsing [D:\test1\prop1.properties]. Message

**Comment by shiamak101** [comment]
Nvr mind, I got it to work.
