### ISSUE TITLE
Empty lines not being trimmed

### ISSUE THREAD

**Issue by AOS-Miracle** [kannanekanath/teamcity-envinject-plugin#5]
I've had an issue for a few days where an empty line after the parameters meant that TeamCity could not understand the imported parameter.

I got this exception from the plug-in: "The line [] does contain property of the form key=value"

**Comment by kannanekanath** [comment]
This is a good point. It makes sense to ignore empty lines! I'll make a fix shortly

**Comment by AOS-Miracle** [comment]
Thank you and thanks for a great little plug-in!

**Comment by kannanekanath** [comment]
Please would you mind trying the version 1.1 of this plugin to see if it ignore empty lines and lines starting with "#". We can close this issue once you have tested this ?

**Comment by AOS-Miracle** [comment]
Sure. I'll close the issue if it works as described.
